spring.application.name=skg-baggage-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/bts_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true